# Generated by Django 4.1.1 on 2022-10-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='cpf')),
                ('age', models.IntegerField(verbose_name='idade')),
            ],
        ),
    ]
